language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: nightly
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - composer test